// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api.proto
// Protobuf Java Version: 4.33.4

package org.nightcode.api.message;

@com.google.protobuf.Generated
public interface MetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nightcode.api.Metadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 generation = 1;</code>
   * @return The generation.
   */
  int getGeneration();

  /**
   * <code>.org.nightcode.api.Trace trace = 2;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.org.nightcode.api.Trace trace = 2;</code>
   * @return The trace.
   */
  org.nightcode.api.message.Trace getTrace();
  /**
   * <code>.org.nightcode.api.Trace trace = 2;</code>
   */
  org.nightcode.api.message.TraceOrBuilder getTraceOrBuilder();

  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  /* nullable */
java.lang.String getTagsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 3;</code>
   */
  java.lang.String getTagsOrThrow(
      java.lang.String key);
}
