// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api.proto
// Protobuf Java Version: 4.33.4

package org.nightcode.api.message;

@com.google.protobuf.Generated
public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nightcode.api.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>.org.nightcode.api.Metadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.org.nightcode.api.Metadata metadata = 2;</code>
   * @return The metadata.
   */
  org.nightcode.api.message.Metadata getMetadata();
  /**
   * <code>.org.nightcode.api.Metadata metadata = 2;</code>
   */
  org.nightcode.api.message.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>.google.protobuf.Any payload = 3;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>.google.protobuf.Any payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.Any getPayload();
  /**
   * <code>.google.protobuf.Any payload = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getPayloadOrBuilder();
}
