// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api.proto
// Protobuf Java Version: 4.33.4

package org.nightcode.api.message;

/**
 * Protobuf type {@code org.nightcode.api.Response}
 */
@com.google.protobuf.Generated
public final class Response extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.nightcode.api.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "Response");
  }
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    service_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.nightcode.api.message.ApiProto.internal_static_org_nightcode_api_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.nightcode.api.message.ApiProto.internal_static_org_nightcode_api_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.nightcode.api.message.Response.class, org.nightcode.api.message.Response.Builder.class);
  }

  private int resultCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ERROR(2),
    CONTENT(3),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 2: return ERROR;
        case 3: return CONTENT;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int SERVICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object service_ = "";
  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  @java.lang.Override
  public java.lang.String getService() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      service_ = s;
      return s;
    }
  }
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceBytes() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      service_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  /**
   * <code>.org.nightcode.api.Status error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return resultCase_ == 2;
  }
  /**
   * <code>.org.nightcode.api.Status error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public org.nightcode.api.message.Status getError() {
    if (resultCase_ == 2) {
       return (org.nightcode.api.message.Status) result_;
    }
    return org.nightcode.api.message.Status.getDefaultInstance();
  }
  /**
   * <code>.org.nightcode.api.Status error = 2;</code>
   */
  @java.lang.Override
  public org.nightcode.api.message.StatusOrBuilder getErrorOrBuilder() {
    if (resultCase_ == 2) {
       return (org.nightcode.api.message.Status) result_;
    }
    return org.nightcode.api.message.Status.getDefaultInstance();
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  /**
   * <code>.google.protobuf.Any content = 3;</code>
   * @return Whether the content field is set.
   */
  @java.lang.Override
  public boolean hasContent() {
    return resultCase_ == 3;
  }
  /**
   * <code>.google.protobuf.Any content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public com.google.protobuf.Any getContent() {
    if (resultCase_ == 3) {
       return (com.google.protobuf.Any) result_;
    }
    return com.google.protobuf.Any.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.Any content = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getContentOrBuilder() {
    if (resultCase_ == 3) {
       return (com.google.protobuf.Any) result_;
    }
    return com.google.protobuf.Any.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(service_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, service_);
    }
    if (resultCase_ == 2) {
      output.writeMessage(2, (org.nightcode.api.message.Status) result_);
    }
    if (resultCase_ == 3) {
      output.writeMessage(3, (com.google.protobuf.Any) result_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(service_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, service_);
    }
    if (resultCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.nightcode.api.message.Status) result_);
    }
    if (resultCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.google.protobuf.Any) result_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.nightcode.api.message.Response)) {
      return super.equals(obj);
    }
    org.nightcode.api.message.Response other = (org.nightcode.api.message.Response) obj;

    if (!getService()
        .equals(other.getService())) return false;
    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 2:
        if (!getError()
            .equals(other.getError())) return false;
        break;
      case 3:
        if (!getContent()
            .equals(other.getContent())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_FIELD_NUMBER;
    hash = (53 * hash) + getService().hashCode();
    switch (resultCase_) {
      case 2:
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.nightcode.api.message.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nightcode.api.message.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nightcode.api.message.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nightcode.api.message.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nightcode.api.message.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nightcode.api.message.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nightcode.api.message.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.nightcode.api.message.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.nightcode.api.message.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.nightcode.api.message.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.nightcode.api.message.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.nightcode.api.message.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.nightcode.api.message.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.nightcode.api.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.nightcode.api.Response)
      org.nightcode.api.message.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nightcode.api.message.ApiProto.internal_static_org_nightcode_api_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nightcode.api.message.ApiProto.internal_static_org_nightcode_api_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.nightcode.api.message.Response.class, org.nightcode.api.message.Response.Builder.class);
    }

    // Construct using org.nightcode.api.message.Response.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      service_ = "";
      if (errorBuilder_ != null) {
        errorBuilder_.clear();
      }
      if (contentBuilder_ != null) {
        contentBuilder_.clear();
      }
      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.nightcode.api.message.ApiProto.internal_static_org_nightcode_api_Response_descriptor;
    }

    @java.lang.Override
    public org.nightcode.api.message.Response getDefaultInstanceForType() {
      return org.nightcode.api.message.Response.getDefaultInstance();
    }

    @java.lang.Override
    public org.nightcode.api.message.Response build() {
      org.nightcode.api.message.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.nightcode.api.message.Response buildPartial() {
      org.nightcode.api.message.Response result = new org.nightcode.api.message.Response(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.nightcode.api.message.Response result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.service_ = service_;
      }
    }

    private void buildPartialOneofs(org.nightcode.api.message.Response result) {
      result.resultCase_ = resultCase_;
      result.result_ = this.result_;
      if (resultCase_ == 2 &&
          errorBuilder_ != null) {
        result.result_ = errorBuilder_.build();
      }
      if (resultCase_ == 3 &&
          contentBuilder_ != null) {
        result.result_ = contentBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.nightcode.api.message.Response) {
        return mergeFrom((org.nightcode.api.message.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.nightcode.api.message.Response other) {
      if (other == org.nightcode.api.message.Response.getDefaultInstance()) return this;
      if (!other.getService().isEmpty()) {
        service_ = other.service_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      switch (other.getResultCase()) {
        case ERROR: {
          mergeError(other.getError());
          break;
        }
        case CONTENT: {
          mergeContent(other.getContent());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              service_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetContentFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object service_ = "";
    /**
     * <code>string service = 1;</code>
     * @return The service.
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     * @return The bytes for service.
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service = 1;</code>
     * @param value The service to set.
     * @return This builder for chaining.
     */
    public Builder setService(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      service_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearService() {
      service_ = getDefaultInstance().getService();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string service = 1;</code>
     * @param value The bytes for service to set.
     * @return This builder for chaining.
     */
    public Builder setServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      service_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        org.nightcode.api.message.Status, org.nightcode.api.message.Status.Builder, org.nightcode.api.message.StatusOrBuilder> errorBuilder_;
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     * @return Whether the error field is set.
     */
    @java.lang.Override
    public boolean hasError() {
      return resultCase_ == 2;
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     * @return The error.
     */
    @java.lang.Override
    public org.nightcode.api.message.Status getError() {
      if (errorBuilder_ == null) {
        if (resultCase_ == 2) {
          return (org.nightcode.api.message.Status) result_;
        }
        return org.nightcode.api.message.Status.getDefaultInstance();
      } else {
        if (resultCase_ == 2) {
          return errorBuilder_.getMessage();
        }
        return org.nightcode.api.message.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     */
    public Builder setError(org.nightcode.api.message.Status value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     */
    public Builder setError(
        org.nightcode.api.message.Status.Builder builderForValue) {
      if (errorBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     */
    public Builder mergeError(org.nightcode.api.message.Status value) {
      if (errorBuilder_ == null) {
        if (resultCase_ == 2 &&
            result_ != org.nightcode.api.message.Status.getDefaultInstance()) {
          result_ = org.nightcode.api.message.Status.newBuilder((org.nightcode.api.message.Status) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 2) {
          errorBuilder_.mergeFrom(value);
        } else {
          errorBuilder_.setMessage(value);
        }
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
        }
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     */
    public org.nightcode.api.message.Status.Builder getErrorBuilder() {
      return internalGetErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     */
    @java.lang.Override
    public org.nightcode.api.message.StatusOrBuilder getErrorOrBuilder() {
      if ((resultCase_ == 2) && (errorBuilder_ != null)) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 2) {
          return (org.nightcode.api.message.Status) result_;
        }
        return org.nightcode.api.message.Status.getDefaultInstance();
      }
    }
    /**
     * <code>.org.nightcode.api.Status error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.nightcode.api.message.Status, org.nightcode.api.message.Status.Builder, org.nightcode.api.message.StatusOrBuilder> 
        internalGetErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        if (!(resultCase_ == 2)) {
          result_ = org.nightcode.api.message.Status.getDefaultInstance();
        }
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.nightcode.api.message.Status, org.nightcode.api.message.Status.Builder, org.nightcode.api.message.StatusOrBuilder>(
                (org.nightcode.api.message.Status) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 2;
      onChanged();
      return errorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> contentBuilder_;
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return resultCase_ == 3;
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.Any getContent() {
      if (contentBuilder_ == null) {
        if (resultCase_ == 3) {
          return (com.google.protobuf.Any) result_;
        }
        return com.google.protobuf.Any.getDefaultInstance();
      } else {
        if (resultCase_ == 3) {
          return contentBuilder_.getMessage();
        }
        return com.google.protobuf.Any.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     */
    public Builder setContent(com.google.protobuf.Any value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        contentBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     */
    public Builder setContent(
        com.google.protobuf.Any.Builder builderForValue) {
      if (contentBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        contentBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     */
    public Builder mergeContent(com.google.protobuf.Any value) {
      if (contentBuilder_ == null) {
        if (resultCase_ == 3 &&
            result_ != com.google.protobuf.Any.getDefaultInstance()) {
          result_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 3) {
          contentBuilder_.mergeFrom(value);
        } else {
          contentBuilder_.setMessage(value);
        }
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     */
    public Builder clearContent() {
      if (contentBuilder_ == null) {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
        }
        contentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     */
    public com.google.protobuf.Any.Builder getContentBuilder() {
      return internalGetContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getContentOrBuilder() {
      if ((resultCase_ == 3) && (contentBuilder_ != null)) {
        return contentBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 3) {
          return (com.google.protobuf.Any) result_;
        }
        return com.google.protobuf.Any.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Any content = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        internalGetContentFieldBuilder() {
      if (contentBuilder_ == null) {
        if (!(resultCase_ == 3)) {
          result_ = com.google.protobuf.Any.getDefaultInstance();
        }
        contentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                (com.google.protobuf.Any) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 3;
      onChanged();
      return contentBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.nightcode.api.Response)
  }

  // @@protoc_insertion_point(class_scope:org.nightcode.api.Response)
  private static final org.nightcode.api.message.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.nightcode.api.message.Response();
  }

  public static org.nightcode.api.message.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.nightcode.api.message.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

