// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api.proto
// Protobuf Java Version: 4.33.4

package org.nightcode.api.message;

@com.google.protobuf.Generated
public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nightcode.api.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>.org.nightcode.api.Status error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.org.nightcode.api.Status error = 2;</code>
   * @return The error.
   */
  org.nightcode.api.message.Status getError();
  /**
   * <code>.org.nightcode.api.Status error = 2;</code>
   */
  org.nightcode.api.message.StatusOrBuilder getErrorOrBuilder();

  /**
   * <code>.google.protobuf.Any content = 3;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>.google.protobuf.Any content = 3;</code>
   * @return The content.
   */
  com.google.protobuf.Any getContent();
  /**
   * <code>.google.protobuf.Any content = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getContentOrBuilder();

  org.nightcode.api.message.Response.ResultCase getResultCase();
}
