// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api.proto
// Protobuf Java Version: 4.33.4

package org.nightcode.api.message;

@com.google.protobuf.Generated
public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nightcode.api.Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; context = 4;</code>
   */
  int getContextCount();
  /**
   * <code>map&lt;string, string&gt; context = 4;</code>
   */
  boolean containsContext(
      java.lang.String key);
  /**
   * Use {@link #getContextMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getContext();
  /**
   * <code>map&lt;string, string&gt; context = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getContextMap();
  /**
   * <code>map&lt;string, string&gt; context = 4;</code>
   */
  /* nullable */
java.lang.String getContextOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; context = 4;</code>
   */
  java.lang.String getContextOrThrow(
      java.lang.String key);
}
