// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api.proto
// Protobuf Java Version: 4.33.4

package org.nightcode.api.message;

@com.google.protobuf.Generated
public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nightcode.api.Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string traceId = 1;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 1;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string spanId = 2;</code>
   * @return The spanId.
   */
  java.lang.String getSpanId();
  /**
   * <code>string spanId = 2;</code>
   * @return The bytes for spanId.
   */
  com.google.protobuf.ByteString
      getSpanIdBytes();

  /**
   * <code>string parentId = 3;</code>
   * @return The parentId.
   */
  java.lang.String getParentId();
  /**
   * <code>string parentId = 3;</code>
   * @return The bytes for parentId.
   */
  com.google.protobuf.ByteString
      getParentIdBytes();
}
